extends:
  - "standard-with-typescript"
parserOptions:
  project: "./tsconfig.json"
rules:
  "semi": [error, always]
  "@typescript-eslint/semi": [error, always]
  "@typescript-eslint/no-extra-semi": error
  "@typescript-eslint/no-non-null-assertion": off
