language: python
python: 3.8
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - "pipenv run find library/jinja2/ -type f -exec curlylint --rule 'indent: 2' {} +"
  - pipenv run flake8
  - pipenv run pytest
  - pipenv run mypy --show-error-codes -m library.models  -m library.utils
services:
  - postgresql
