version: '3.7'

services:
  app:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate &&
        env HIVEMIND_PROCESSES=dev_web,worker /go/bin/hivemind
    ports:
      - '8080:8080'
    volumes:
      - .:/app

volumes:
  data:
