[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "booklogger.settings"
addopts = "--nomigrations --cov=booklogger --cov=library --cov-report term-missing:skip-covered --cov-fail-under=78 --no-cov-on-fail -n auto"
norecursedirs = "library/jinja2/library"

[tool.coverage.report]
omit = [
        "*/settings.py",
        "*/urls.py",
        "booklogger/?sgi.py",
        "library/migrations/*",
        "library/tests/*"
    ]

[tool.mypy]
files = ["booklogger", "library"]
exclude = "/(migrations|tests|jinja2)/$"
pretty = true
show_error_codes = true

check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
no_implicit_reexport = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

plugins = ["mypy_django_plugin.main"]

# disabled at least until typeddjango/django-stubs#700 is fixed
cache_dir = "/dev/null"
no_incremental = true

[tool.django-stubs]
django_settings_module = "booklogger.settings"

[tool.isort]
profile = "black"

[tool.ruff]
extend-exclude = [
        "library/migrations/*",
        "library/tests/*",
]
select = ["ALL"]
ignore = [
        "E501",
        "D",
        "ANN", # annotations: let mypy do it
        "COM", # seems to conflict with black

        "A003", # TODO Class attribute `id` is shadowing a python builtin
        "ARG001", # TODO Unused function argument
        "BLE001", # TODO Do not catch blind exception: `Exception`
        "C901", # TODO function is too complex
        "EM101", # TODO Exception must not use a string literal, assign to variable first
        "EM102", # TODO Exception must not use an f-string literal, assign to variable first
        "ERA001", # TODO Found commented-out code
        "F841", # TODO Local variable `count` is assigned to but never used
        "FBT001", # TODO Boolean positional arg in function definition
        "FBT002", # TODO Boolean default value in function definition
        "PGH003", # TODO Use specific rule codes when ignoring type issues
        "PLR2004", # TODO Magic value used in comparison
        "RET504", # TODO Unnecessary variable assignment before `return` statement
        "RUF001", # TODO String contains ambiguous unicode character
        "RUF100", # TODO Unused `noqa` directive
        "S113", # TODO Probable use of requests call without timeout
        "T201", # TODO `print` found
]
