[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "booklogger.settings"
addopts = "--nomigrations --cov=booklogger --cov=library --cov-report term-missing:skip-covered --cov-report xml"

[tool.coverage.report]
omit = [
        "*/__init__.py",
        "library/migrations/*"
    ]

[tool.github-coverage-action]
threshold = 40
