# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Lint with curlylint
        run: |
          pipenv run find library/jinja2/ -name '*.html' -exec curlylint --rule 'indent: 2' {} +
      - name: Lint with flake8
        run: |
          pipenv run flake8
      - name: Lint with mypy
        run: |
          pipenv run mypy --show-error-codes -m library.models  -m library.utils -m library.forms
      - name: Test with pytest
        run: |
          export DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/github_actions
          pipenv run pytest
