# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/github_actions
      PIPENV_VENV_IN_PROJECT: enabled

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        id: setup-python
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('Pipfile.lock') }}
        id: cache
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
      - name: Lint with curlylint
        run: |
          pipenv run find library/jinja2/ -name '*.html' -exec curlylint --rule 'indent: 2' {} +
      - name: Lint with flake8
        run: |
          pipenv run flake8
      - name: Lint with mypy
        run: |
          pipenv run mypy --show-error-codes -m library.models  -m library.utils -m library.forms
      - name: Test with pytest
        run: |
          pipenv run pytest
      - name: Check code coverage
        run: |
          pipenv run ./scripts/check-coverage.py
