# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/github_actions

    steps:
      - uses: actions/checkout@v2
      - name: Detect Python version
        id: detect-python
        run: |
          echo "::set-output name=python-version::$(sed -r 's/^(python-)?(3\.[0-9]+)\.[0-9]+$/\2/' runtime.txt)"
      - name: Set up Python ${{ steps.detect-python.outputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.detect-python.outputs.python-version }}
        id: setup-python
      - uses: actions/cache@v2
        with:
          path: ~/.venv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-hashFiles('requirements-dev.txt') }}
        id: cache
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ~/.venv
          . ~/.venv/bin/activate
          pip install -r requirements.txt -r requirements-dev.txt
      - name: pre-commit
        run: |
          . ~/.venv/bin/activate
          pre-commit run --all-files
