# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python: [3.8, 3.9]

    env:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/github_actions

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
        id: setup-python
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
        id: cache
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: Lint with curlylint
        run: |
          poetry run find library/jinja2/ -name '*.html' -exec curlylint --rule 'indent: 2' {} +
      - name: Lint with flake8
        run: |
          poetry run flake8
      - name: Lint with mypy
        run: |
          poetry run mypy --show-error-codes --exclude '/(migrations|tests|management)/$' booklogger library
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Check code coverage
        run: |
          poetry run ./scripts/check-coverage.py
